name: Petopia Market

on:
  push: # Trigger the workflow on push events to the specified branches
    branches:
      - main
      - dev
  pull_request: # Trigger the workflow on pull requests targeting the specified branches
    branches:
      - dev

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest # Define the operating system for the job
    strategy:
      matrix: # Define a matrix for running tests with different configurations
        node-version: [20.x]
        mongodb-version: ["6.0"]

    steps:
      - name: Checkout code # Step to checkout the repository code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} # Step to set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB # Step to start MongoDB service
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Install backend dependencies
        run: |
          cd Backend
          npm i

      - name: Run backend tests
        env:
          ACCESS_TOKEN_SECRET: 7c03530c201384fccfd27066298655a3fbcc5538ca674c81e1ec1ea2320a243f53b6629a2e3013b09ac694e5f650e76fa6bb92f93a18e2855011400dc0861bd5
          REFRESH_TOKEN_SECRET: 29883be9b570d00fedb353ba53f7f239ebd0215ce9b1dd99ec540d63f861c152920f0fa526f42d894108375ba61154188709d29ea508d2087cb0c00040921432
          ACCESS_TOKEN_EXPIRY: 2d
          REFRESH_TOKEN_EXPIRY: 15d
        run: |
          cd Backend
          npm run test
